config/routes.rb
Rails.application.routes.draw do
  resources :tasks do 
    collection do 
      get :filter
    end
  end

  # general user
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  get 'password', to: 'password#edit', as: :edit_password
  patch 'password', to: 'password#update'

  delete 'logout', to: 'sessions#destroy'

  # admin user
  namespace :admin do 
    root 'users#index'
    resources :users
  end

  root 'tasks#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
  validates :status, presence: true

  scope :sort_by_endtime, -> { order(end_time: :asc) }
  scope :sort_by_createtime, -> { order(created_at: :desc) }
  scope :sort_by_level_desc, -> { order(level: :desc) }
  scope :sort_by_level_asc, -> { order(level: :asc) }

  def self.search(title = '', status = '')
    if title != '' || status != ''
      Task.where("title ILIKE ? AND status LIKE ?", "%#{title}%", "%#{status}%")
    else
      Task.sort_by_createtime
    end

  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :tasks, :dependent => :destroy

  validates :email, presence: true, uniqueness: true

  enum role: {
    user: 0, 
    admin: 1,
    master: 2
  }

  u1 = User.find_by(email: 'terry@gmail.com')
  u2 = User.find_by(email: 'seed@gmail.com')
  u1.update_attribute(:role, 2) if u1 != nil
  u2.update_attribute(:role, 2) if u2 != nil

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'backend'
  before_action :admin_user

  def admin_user
    redirect_to :root, notice: '需要管理員權限' unless Current.user.role == 'admin' || Current.user.role == 'master'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :find_user, only: [:edit, :show, :update, :destroy]
  
  def index 
    @users = User.order(created_at: :desc)
  end

  def new 
    @user = User.new
  end

  def create 
    @user = User.new(user_params)

    if @user.save 
      redirect_to :admin_root, notice: '使用者新增成功'
    else 
      render :new
    end

  end

  def show 
    @tasks = @user.tasks
  end

  def edit
  end

  def update

    if @user.update(user_params) 
      redirect_to :admin_root, notice: '使用者更新成功'
    else 
      render :edit
    end

  end

  def destroy 
    @user.destroy

    redirect_to :admin_root
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end

  def find_user 
    @user = User.find_by(id: params[:id])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  # unless Rails.env.test? 
  #   http_basic_authenticate_with :name => ENV["HTTP_BASIC_USER"], 
  #                                :password => ENV["HTTP_BASIC_PASSWORD"] 
  # end

  def set_current_user
    if session[:user_id] 
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_logged_in
    redirect_to sign_in_path, alert: "請先登入" if Current.user.nil?
  end

end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_logged_in

  def edit 

  end

  def update
    if Current.user.update(password_params)
      redirect_to :root, notice: "密碼更新成功！"
    else 
      render :edit
    end
  end
  
  private 

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new 
    @user = User.new
  end

  def create 
    @user = User.new(user_params)

    if @user.save 
      session[:user_id] = @user.id
      redirect_to :root, notice: '會員註冊成功'
    else 
      render :new
    end

  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new 
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id

      redirect_to :root, notice: "登入成功"
    else 
      flash[:alert] = '信箱或密碼輸入錯誤'
      render :new
    end

  end

  def destroy 
    session[:user_id] = nil
    redirect_to :root, notice: '已登出'
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_logged_in
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index 
    @tasks = Current.user.tasks.sort_by_createtime
    # @tasks = Task.sort_by_createtime
  end

  def new 
    @task = Current.user.tasks.new
  end

  def create 
    @task = Current.user.tasks.build(task_params)
    # @task = Task.new(task_params)

    if @task.save
      redirect_to :root, notice: "任務新增成功！"
    else 
      render :new
    end

  end

  def show 
  end

  def edit 
  end

  def update 

    if @task.update(task_params)
      redirect_to task_path(@task), notice: "任務更新成功！"
    else
      render :edit
    end
  end

  def destroy 
    @task.destroy
    redirect_to :root, notice: "任務已刪除"
  end

  def filter 

    @tasks = Current.user.tasks
    @tasks = sort_task(params[:sort], @tasks) if params[:sort]
    @tasks = @tasks.search(params[:title], params[:status])

    render json: {tasks: @tasks }

  end


  private 
  def task_params 
    params.require(:task).permit(:title, :content, :end_time, :status, :search, :level)
  end

  def find_task 
    @task = Current.user.tasks.find(params[:id])
  end

  def sort_task(sort = 'create_time', tasks = nil)
    case sort
    when "end_time"
      @tasks = tasks.sort_by_endtime
    when "create_time"
      @tasks = tasks.sort_by_createtime
    when "level_desc" 
      @tasks = tasks.sort_by_level_desc
    when "level_asc" 
      @tasks = tasks.sort_by_level_asc
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper 
  def form_action(task) 
    if task.id.present? 
      '更新任務'
    else
      '新增任務'
    end
  end
end

app/helpers/task_helper.rb
module TaskHelper
  def levelToWord(level)
    case level 
    when 0 
      return "低"
    when 1
      return "中"
    when 2 
      return "高"
    end
  end
end

app/views/admin/users/_editform.html.erb
<%= form_with model: user, url: admin_user_path do |form| %>
<div class="user-form-error">
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>  
</div>

  <div class="user-email">
    <%= form.label :email, '信箱' %>
    <%= form.text_field :email, placeholder: 'user@gmail.com' %>
  </div>
  
  <div class="user-password">
    <%= form.label :password, '密碼' %>
    <%= form.password_field :password %>
  </div>

  <div class="user-password-confirmation">
    <%= form.label :password_confirmation, '確認密碼' %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="user-role">
    <%= form.label :role, '角色' %>

    <div class="normal">
      <%= form.label :role_0, "使用者" %>
      <%= form.radio_button :role, "user", checked: true %>
    </div>
    
    <div class="admin">
      <%= form.label :role_1, "管理員" %>
      <%= form.radio_button :role, "admin" %>
    </div>
  
  </div>

  <%= form.submit %>
<% end %>

app/views/admin/users/_newform.html.erb
<%= form_with model: user, url: admin_users_path do |form| %>
<div class="user-form-error">
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>  
</div>

  <div class="user-email">
    <%= form.label :email, '信箱' %>
    <%= form.text_field :email, placeholder: 'user@gmail.com' %>
  </div>
  
  <div class="user-password">
    <%= form.label :password, '密碼' %>
    <%= form.password_field :password %>
  </div>

  <div class="user-password-confirmation">
    <%= form.label :password_confirmation, '確認密碼' %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="user-role">
    <%= form.label :role, '角色' %>

    <div class="normal">
      <%= form.label :role_0, "使用者" %>
      <%= form.radio_button :role, "user", checked: true %>
    </div>
    
    <div class="admin">
      <%= form.label :role_1, "管理員" %>
      <%= form.radio_button :role, "admin" %>
    </div>
  
  </div>

  <%= form.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="member-system">
  
  <div class="container">
    <div class="member-card">
      <h1 class="title">更新會員</h1>
      <%= render 'editform', user: @user %>

      <%= link_to :admin_root, class: 'back' do %>
        <i class="fas fa-arrow-left"></i>回管理者列表
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container admin">
  <h1>會員列表</h1>

  <nav class="action">
    <ul>
      <li><%= link_to '新增使用者', new_admin_user_path %></li>
    </ul>
  </nav>

  <table class="user-table">
    <thead>
      <tr>
        <th>會員帳號</th>
        <th>會員權限</th>
        <th>任務數量</th>
        <th>任務列表</th>
        <th>編輯會員</th>
        <th>刪除會員</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% if user.role != 'master' %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.role %></td>
          <td><%= user.tasks.count %></td>
          <td><%= link_to '任務列表', admin_user_path(user.id) %></td>
          <td><%= link_to '編輯', edit_admin_user_path(user.id) %></td>
          <td class="delete"><%= link_to '刪除', admin_user_path(user.id), method: 'delete', data: {confirm: '確定要刪除該使用者'} %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/new.html.erb
<div class="member-system">
  
  <div class="container">
    <div class="member-card">
      <h1 class="title">新增會員</h1>
      <%= render 'newform', user: @user %>

      <%= link_to :admin_root, class: 'back' do %>
        <i class="fas fa-arrow-left"></i>回管理者列表
      <% end %>
    </div>

  </div>
</div>

app/views/admin/users/show.html.erb
<div class="tasks-table">
  <div class="container">
    <div class="row">
      <% @tasks.each do |task| %>
        <div class="col-3">
          <div class="task" data-title="<%= task.title %>" data-title="<%= task.title %>">
            <h3 class="title"><%= task.title %></h3>

            <div class="status-wrap">
              <h4>狀態：</h4>
              <span><%= task.status %></span>
            </div>
         
            <div class="order-wrap">
              <h4>優先順序：</h4>
              <span><%= levelToWord(task.level) if task.level %></span>
            </div>

            <% if task.end_time %>
            <div class="end-time-wrap">
              <h4>結束時間：</h4>
              <span><%= task.end_time.strftime("%Y/%m/%d") %></span>
            </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <%= link_to :admin_root, class: 'back' do %>
      <i class="fas fa-arrow-left"></i>回管理者列表
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400;700&display=swap" rel="stylesheet">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager 管理系統</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400;700&display=swap" rel="stylesheet">

    <%= stylesheet_pack_tag 'backend', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'backend', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/backend/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/password/edit.html.erb
<div class="member-system">
  
  <div class="container">
    <div class="member-card">
      <h1 class="title">更改密碼</h1>
      <%= form_with model: Current.user, url: edit_password_path do |form| %>
        <div class="user-form-error">
          <% if form.object.errors.any? %>
            <% form.object.errors.full_messages.each do |message| %>
              <p><%= message %></p>
            <% end %>
          <% end %>  
        </div>
      
        <div class="user-password">
          <%= form.label :password, '密碼' %>
          <%= form.password_field :password %>
        </div>
  
        <div class="user-password-confirmation">
          <%= form.label :password_confirmation, '確認密碼' %>
          <%= form.password_field :password_confirmation %>
        </div>
    
    
        <%= form.submit '更改密碼' %>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/search.js.erb
<!-- document.querySelector(".tasks-table").innerHTML = '<%= j (render "/tasks/task", tasks: @tasks) %>' -->

app/views/shared/_navbar.html.erb
<header>
  <div class="logo">
    <h1>任務列表</h1>
  </div>
  
  <div class="nav-bar">
    <nav class="user">
      <ul>
        <% if Current.user %>
          <li class="user-email"><%= Current.user.email %></li>
          <li><%= link_to '登出', logout_path, method: :delete %></li>
          <li><%= link_to '更改密碼', edit_password_path %></li>
        <% else %>
          <li><%= link_to '註冊', sign_up_path %></li>
          <li><%= link_to '登入', sign_in_path %></li>
          <li><%= link_to '更改密碼', edit_password_path %></li>
        <% end %>
      </ul>
  
    </nav>
  </div>
</header>

<% flash.each do |type, msg| %>
  <div class="flash-error"><%= msg %></div>
<% end %>

app/views/shared/backend/_navbar.html.erb
<header>
  <div class="logo">
    <h1>管理員系統</h1>
  </div>
  
  <div class="nav-bar">
    <nav class="user">
      <ul>
        <% if Current.user %>
          <li class="user-email"><%= Current.user.email %></li>
          <li><%= link_to '登出', logout_path, method: :delete %></li>
          <li><%= link_to '更改密碼', edit_password_path %></li>
        <% else %>
          <li><%= link_to '註冊', sign_up_path %></li>
          <li><%= link_to '登入', sign_in_path %></li>
        <% end %>
      </ul>
  
    </nav>
  </div>
</header>

<% flash.each do |type, msg| %>
  <div class="flash-error"><%= msg %></div>
<% end %>

app/views/tasks/_form.html.erb
<div class="task-card form">
  <%= form_with model: task do |form| %>
    <div class="task-title">
      <%= form.label :title, '任務標題' %><br>
      <%= form.text_field :title %>
    </div>
   
    <div class="task-content">
      <%= form.label :content, '任務內容' %><br>
      <%= form.text_area :content, size: "30x10" %>
    </div>

    <div class="task-end-time">
      <%= form.label :end_time, '結束時間' %><br>
      <%= form.date_field :end_time, size: "30x10" %>
    </div>
  
    <div class="task-status">
      <span>任務狀態</span>
      <%= form.radio_button :status, "待處理", checked: true %>
      <%= form.label :status_待處理, "待處理" %>

      <%= form.radio_button :status, "處理中" %>
      <%= form.label :status_處理中, "處理中" %>
    
      <%= form.radio_button :status, "完成" %>
      <%= form.label :status_完成, "完成" %>
    </div>
    
    <div class="task-level">
      <span class="title">優先順序</span>
      <%= form.radio_button :level, "0", checked: true %>
      <%= form.label :level_0, "低" %>
    
      <%= form.radio_button :level, "1" %>
      <%= form.label :level_1, "中" %>
    
      <%= form.radio_button :level, "2" %>
      <%= form.label :level_2, "高" %>
    </div>

    <%= form.submit form_action(task), class: 'update-btn' %>
    
  <% end %>
  
  

</div>

app/views/tasks/_task.html.erb
<% @tasks.each do |task| %>
<div class="col-3">
  <div class="task" data-title="<%= task.title %>" data-title="<%= task.title %>">
    <%= link_to task_path(task) do %>
      <h3 class="title"><%= task.title %></h3>
      <div class="status-wrap">
        <h4>狀態：</h4>
        <span><%= task.status %></span>
      </div>
      
      <div class="order-wrap">
        <h4>優先順序：</h4>
        <span><%= levelToWord(task.level) if task.level %></span>
      </div>
      
      <div class="content-wrap">
        <h4>任務內容：</h4>
        <div class="content"><%= task.content %></div>
      </div>
      
      <% if task.end_time %>
      <div class="end-time-wrap">
        <h4>結束時間：</h4>
        <span><%= task.end_time.strftime("%Y/%m/%d") %></span>
      </div>
      <% end %>
    <% end %>
  </div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<div class="task-card-wrapper">
  <h1>編輯任務</h1>
  
  <%= render 'form', task: @task %>

  <%= link_to task_path(params[:id]), class: 'back' do %>
    <i class="fas fa-arrow-left"></i>回任務
  <% end %>
  <%= link_to :root, class: 'back' do %>
    <i class="fas fa-arrow-left"></i>回列表
  <% end %>
</div>

app/views/tasks/index.html copy.erb
<header>
  <h1>任務列表</h1>
</header>
<div class="container">
  
  <%= @task_title %>
  
  <div class="task-wrapper">
    <div class="table-action">
      <%= link_to '新增任務', new_task_path %>
  
      <h3>按時間排序</h3>
      <ul>
        <li><%= link_to '按結束時間排序', tasks_path(sort: 'end_time'), id: 'end_time_btn' %></li>
        <li><%= link_to '按新增時間排序', tasks_path(sort: 'create_time'), id: 'create_time_btn' %></li>
      </ul>
    
      <h3>按優先順序排序</h3>
      <ul>
        <li><%= link_to '從高到低', tasks_path(sort: 'level_desc'), id: 'level_desc_btn' %></li>
        <li><%= link_to '從低到高', tasks_path(sort: 'level_asc'), id: 'level_asc_btn' %></li>
      </ul>
      
      <h3>搜尋任務</h3>
      <%= form_with(url: filter_tasks_path, method: :get, class: 'search-form') do |f| %>
        <%= f.text_field :title, class: 'search-title', placeholder: '搜尋任務名稱' %>
        
        <%= f.radio_button :status, '全部' %> 
        <%= label :status, '全部' %>
        <%= f.radio_button :status, '待處理' %> 
        <%= label :status, '待處理' %>
        <%= f.radio_button :status, '處理中' %> 
        <%= label :status, '處理中' %>
        <%= f.radio_button :status, '完成' %>
        <%= label :status, '完成' %>
    
        <%= f.submit "Search", class: 'submit-btn', style: "display:none" %>
      <% end %>
    </div>

    <div class="tasks-table">
      <div class="container">
        <div class="row">
          <%= render '/tasks/task', tasks: @tasks if @tasks %>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/tasks/index.html.erb
<div class="container">
  
  <%= @task_title %>
  
  <div class="task-wrapper">
    <div class="table-action">
      <%= link_to '新增任務', new_task_path %>
  
      <h3>按時間排序</h3>
      <ul>
        <li><a class="sort-btn end_time" href="#" data-action="end_time">按結束時間排序</a></li>
        <li><a class="sort-btn" href="#" data-action="create_time">按新增時間排序</a></li>
      </ul>
    
      <h3>按優先順序排序</h3>
      <ul>
        <li><a class="sort-btn" href="#" data-action="level_desc">從高到低</a></li>
        <li><a class="sort-btn" href="#" data-action="level_asc">從低到高</a></li>
      </ul>
      
      <h3>搜尋任務</h3>
      <%= form_with(url: filter_tasks_path, method: :get, class: 'search-form') do |f| %>
        <%= f.text_field :title, class: 'search-title', placeholder: '搜尋任務名稱' %>
        
        <%= f.radio_button :status, '全部' %> 
        <%= label :status, '全部' %>
        <%= f.radio_button :status, '待處理' %> 
        <%= label :status, '待處理' %>
        <%= f.radio_button :status, '處理中' %> 
        <%= label :status, '處理中' %>
        <%= f.radio_button :status, '完成' %>
        <%= label :status, '完成' %>
    
        <%= f.submit "Search", class: 'submit-btn', style: "display:none" %>
      <% end %>
    </div>

    <div class="tasks-table">
      <div class="container">
        <div class="row">
          <%= render '/tasks/task', tasks: @tasks if @tasks %>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/tasks/index.js.erb
document.querySelector(".tasks-table").innerHTML = '<%= j (render "/tasks/task", tasks: @tasks) %>'
document.querySelector('nav.pagination').innerHTML = '<%= j (paginate(@tasks).to_s) %>';

app/views/tasks/new.html.erb
<div class="task-card-wrapper">
  <h1>新增任務</h1>

  <% if @task.errors.any? %>
    <ul>
      <% @task.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= render 'form', task: @task %>
</div>

app/views/tasks/search.js.erb
document.querySelector(".tasks-table").innerHTML = '<%= j (render "/tasks/task", tasks: @tasks) %>'

app/views/tasks/show.html.erb
<div class="task-card-wrapper">
  <div class="task-card">
    <div class="task-info">
      <h2 class="title"><%= @task.title %></h2>

      <div class="level">
        <span>優先順序：</span>
        <span><%= levelToWord(@task.level) %></span>
      </div>

      <div class="date">
        <span>結束時間：</span>
        <span><%= @task.end_time.strftime("%Y/%m/%d") if @task.end_time %></span>
      </div>
  
      <div class="status">
        <span>狀態：</span>
        <span><%= @task.status %></span>
      </div>
  
      <div class="content">
        <span>任務內容：</span>
        <p><%= @task.content %></p>
      </div>

      
  
    </div>
  
    <div class="link">
      
      <%= link_to edit_task_path(@task), class: 'shadow-btn' do %>
        <i class="far fa-edit"></i>
      <% end %>
      <%= link_to task_path(@task), method: 'DELETE', data: { confirm: '確定要刪除任務？' }, class: 'shadow-btn' do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </div>
    
  
    <%= link_to :root, class: 'back' do %>
      <i class="fas fa-arrow-left"></i>回列表
    <% end %>
  </div>
</div>